CREATE TABLE "cakes" (
	"id" serial PRIMARY KEY NOT NULL,
	"type" text,
	"slug" text,
	"title" text,
	"description_short" text,
	"description_one" text,
	"description_two" text,
	"description_three" text,
	"image_1_small" text,
	"image_1_big" text,
	"image_2_small" text,
	"image_2_big" text,
	"image_3_small" text,
	"image_3_big" text,
	"image_4_small" text,
	"image_4_big" text,
	"image_5_small" text,
	"image_5_big" text,
	"image_6_small" text,
	"image_6_big" text,
	"meta_title" text,
	"meta_description" text,
	"weight" integer,
	"width" integer,
	"height" integer,
	"price" integer,
	"discount" integer,
	"discount_price" integer,
	"ingredients" text,
	"calories" text,
	"protein" text,
	"fat" text,
	"carbohydrates" text,
	"badge" text,
	"rating" integer,
	"visibility" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "comments" (
	"order_id" serial PRIMARY KEY NOT NULL,
	"date" text,
	"product_id" integer,
	"product_image" text,
	"product_title" text,
	"user_name" text,
	"user_rating" integer,
	"user_comment" text,
	"visibility" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "orders" (
	"order_id" serial PRIMARY KEY NOT NULL,
	"order_number" text,
	"order_date" text,
	"delivery_type" text,
	"total_cart_count" integer,
	"total_cart_sum" integer,
	"cart_samovyvoz_bonus" integer,
	"total_order_sum" integer,
	"delivery_sum" integer,
	"user_bonus" integer,
	"user_name" text,
	"user_phone" text,
	"user_city" text,
	"user_street" text,
	"user_building" text,
	"user_entrance" text,
	"user_flat" text,
	"user_floor" text,
	"user_comment" text,
	"cart_list" json,
	"status_accept" text,
	"status_delivery" text,
	"status_complete" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pastry" (
	"id" serial PRIMARY KEY NOT NULL,
	"type" text,
	"slug" text,
	"title" text,
	"description_short" text,
	"description_one" text,
	"description_two" text,
	"description_three" text,
	"image_1_small" text,
	"image_1_big" text,
	"image_2_small" text,
	"image_2_big" text,
	"image_3_small" text,
	"image_3_big" text,
	"image_4_small" text,
	"image_4_big" text,
	"image_5_small" text,
	"image_5_big" text,
	"image_6_small" text,
	"image_6_big" text,
	"meta_title" text,
	"meta_description" text,
	"weight" integer,
	"width" integer,
	"height" integer,
	"price" integer,
	"discount" integer,
	"discount_price" integer,
	"ingredients" text,
	"calories" text,
	"protein" text,
	"fat" text,
	"carbohydrates" text,
	"badge" text,
	"rating" integer,
	"visibility" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"user_id" serial PRIMARY KEY NOT NULL,
	"user_name" text,
	"user_email" text,
	"user_password" text,
	"user_role" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
